Table Simulations {
  Id int [primary key]
  SimulationType int
  Status int
  RequestedAt DateTime
  StartedAt DateTime
  CompletedAt DateTime?
  VideoPath varchar
}

Table Chickens {
  Id int [primary key]
  Name string
  Wins int
}

Table SimulationChickens{
  SimulationId int
  ChickenId int
  Position int
}

Table FindSimulationConfiguration{
  SimulationId int [primary key]
  Speed float
}

Table FindSimulationResult{
  SimulationId int [primary key]
  Score int;
}

Table RaceSimulationConfiguration{
  SimulationId int [primary key]
}

Table RaceSimulationResult{
  SimulationId int [primary key]
  WinnerId int
}


Ref: "SimulationChickens"."SimulationId" ?>? "Simulations"."Id"

Ref: "SimulationChickens"."ChickenId" ?>? "Chickens"."Id"

Ref: "RaceSimulationResults"."WinnerId" ?>? "Chickens"."Id"

Ref: "Simulations"."Id" -? "RaceSimulationConfiguration"."SimulationId"

Ref: "Simulations"."Id" -? "RaceSimulationResults"."SimulationId"