Table Simulations {
  Id int [pk, increment]
  Name nvarchar [not null]
  SimulationType int [not null, note: 'Find=0, Race=1, Sumo=2, Balance=3']
  SimulationStatus int [not null, note: 'Requested=0, Creating=1, Ready=2, InProgress=3, Completed=4']
  Contestants int [not null]
  RequestedAt datetime [not null]
  StartedAt datetime
  CompletedAt datetime
  VideoPath nvarchar [not null]
}

Table Chickens {
  Id int [pk, increment]
  Name nvarchar [not null]
  Wins int [not null]
}

Table SimulationChickens {
  SimulationId int [not null]
  ChickenId int [not null]

  indexes {
    (SimulationId, ChickenId) [pk]
    ChickenId
  }
}

Table FindSimulationConfigurations {
  SimulationId int [pk]
  Speed float [not null]
}

Table FindSimulationResults {
  SimulationId int [pk]
  Wins int [not null]
}

Table RaceSimulationConfigurations {
  SimulationId int [pk]
}

Table RaceSimulationResults {
  SimulationId int [pk]
  WinnerChickenId int
}

Ref: SimulationChickens.SimulationId > Simulations.Id [delete: cascade]
Ref: SimulationChickens.ChickenId > Chickens.Id [delete: restrict]

Ref: FindSimulationConfigurations.SimulationId - Simulations.Id [delete: cascade]
Ref: FindSimulationResults.SimulationId - Simulations.Id [delete: cascade]
Ref: RaceSimulationConfigurations.SimulationId - Simulations.Id [delete: cascade]
Ref: RaceSimulationResults.SimulationId - Simulations.Id [delete: cascade]
