@NeuralChickens.Api_HostAddress = https://localhost:7231


@id = 0

POST {{NeuralChickens.Api_HostAddress}}/api/simulations/{{id}}/start

###

GET {{NeuralChickens.Api_HostAddress}}/api/simulations/{{id}}/video

###

GET {{NeuralChickens.Api_HostAddress}}/api/simulations/{{id}}

###
